Feat/login screen
karlgama/contactless pull request #6
Opened 2023-09-19 23:02 UTC by karlgama

2023-09-19 23:42 UTC, freirezinho requested changes
Precisa reorganizar o código no padrão MVVM + Clean Arch

2023-09-19 23:42 UTC, freirezinho commented on .idea/.gitignore
Qual o propósito de apagar a pasta .idea?

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/res/values/strings.xml
> +    <string name="web_client_id">887634639920-ga0fa5d51suuop11jimmaedo6alqimul.apps.googleusercontent.com</string>
Geralmente aqui ficam mais mensagens voltadas ao usuário, coisa que precisa de tradução, strings dessa natureza. Constantes como essa aí deveriam ir para uma classe de constantes.

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/res/mipmap-xxxhdpi/undraw_card_foreground.png
Esse PNG está esquisito, não devia ter esse fundo branco.

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/res/mipmap-xxxhdpi/lock_round.png
A intenção foi boa, mas podia ter me pedido o app icon

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/ui/components/KeyCard.kt
> +                        UUID.randomUUID().toString(),
Ao invés de fazer isso, o correto seria ele receber qual texto exibir

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/ui/components/KeyCard.kt
> +                        stringResource(R.string.key_from),
Aqui tem que ter uma concatenação com um nome de usuário que o componente receber

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/infra/database/models/SignInResult.kt
Em questão de organização, acho que são coisas separadas, não? UserData, se for um DAO para o Room, até pode ficar aqui. SignInResult devia estar junto das coisas de autenticação.

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/ui/GoogleAuthUiClient.kt
> +class GoogleAuthUiClient constructor(
Se isso é UI, n devia ser uma função @composable ?

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/ui/GoogleAuthUiClient.kt
> +class GoogleAuthUiClient constructor(
Por tudo o que faz, me parece que encaixaria melhor como viewModel...

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/ui/GoogleAuthUiClient.kt
> +    suspend fun signIn(): IntentSender? {
Seria interessante desacoplar o corpo desse método em um UseCase

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/ui/GoogleAuthUiClient.kt
> +    suspend fun signInWithIntent(intent: Intent): SignInResult {
Seria interessante desacoplar o corpo desse método em um UseCase

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/ui/GoogleAuthUiClient.kt
> +    suspend fun signOut() {
Seria interessante desacoplar o corpo desse método em um UseCase

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/ui/GoogleAuthUiClient.kt
> +    fun getSignedInUser(): UserData? = auth.currentUser?.run {
Seria interessante desacoplar o corpo desse método em um UseCase

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/ui/GoogleAuthUiClient.kt
> +    private fun buildSignInRequest(): BeginSignInRequest {
Isso aqui podia ser uma extensão estática de BeginSignInRequest

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/MainActivity.kt
> +                Screen.ActiveKeys, Screen.Settings, Screen.SignIn
Acredito que o certo seria tratar isso fora da navigationBar. Devia ser uma tela que não aparece junto com as outras, mas antes. No login bem sucedido, vem para esse tipo de navegação aqui, com as tabs e tudo mais.

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/MainActivity.kt
> +                            })
A viewModel está bem vazia. Muito disso poderia estar sendo tratado nela, por meio de use cases. Ela tbm n deve ser instanciada, o Hilt cuida de injetá-la como dependência e vc pode chamar direto dentro do componente da tela, como demonstrado na ActiveKeysScreen.

2023-09-19 23:42 UTC, freirezinho commented on app/src/main/java/impacta/contactless/features/login/SignInScreen.kt
> +    onSignInClick: () -> Unit
Esse onSignInClick poderia ser removido desse constructor; poderia usar a viewModel dentro desse componente by hiltViewModel e então usar o método da viewModel no botão

2023-09-20 00:15 UTC, karlgama commented on .idea/.gitignore
são apenas configurações de ide, sujeira basicamente

2023-09-20 00:16 UTC, karlgama commented on app/src/main/java/impacta/contactless/MainActivity.kt
> +                Screen.ActiveKeys, Screen.Settings, Screen.SignIn
eu pensei nisso, só não sei como faria pra dizer q a tela de login é a primeira, acho q era no manifest.xml

2023-09-20 00:19 UTC, karlgama commented on app/src/main/java/impacta/contactless/ui/components/KeyCard.kt
> +                        UUID.randomUUID().toString(),
fiz isso apenas pra ver como ficava na hora q estava fazendo essa parte

2023-11-22 02:38 UTC, closed without merging